import 'package:flutter/material.dart';
import '../../data/models/event.dart';
import '../../data/repositories/event_repository.dart';

class AddEventScreen extends StatefulWidget {
  @override
  _AddEventScreenState createState() => _AddEventScreenState();
}

class _AddEventScreenState extends State<AddEventScreen> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _dateController = TextEditingController();
  final _timeController = TextEditingController();
  final _venueController = TextEditingController();
  final _avenueController = TextEditingController();
  final _descriptionController = TextEditingController();
  final _contentController = TextEditingController();
  final _contactController = TextEditingController();
  final _imageUrlController = TextEditingController();

  final EventRepository _eventRepository = EventRepository();
  List<String> _imageUrls = []; // Stores multiple image URLs

  void _addImageUrl() {
    if (_imageUrlController.text.isNotEmpty) {
      setState(() {
        _imageUrls.add(_imageUrlController.text);
        _imageUrlController.clear();
      });
    }
  }

  void _submitEvent() async {
    if (_formKey.currentState!.validate()) {
      Event newEvent = Event(
        id: '', // Auto-generated by the backend
        name: _titleController.text,
        date: _dateController.text,
        time: _timeController.text,
        venue: _venueController.text,
        avenue: _avenueController.text,
        description: _descriptionController.text,
        content: _contentController.text,
        contact: _contactController.text,
        featuredImage: _imageUrls.isNotEmpty ? _imageUrls[0] : '',
        images: _imageUrls, // List of image URLs
      );

      bool success = await _eventRepository.addEvent(newEvent);

      if (success) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text("Event added successfully")));
        Navigator.pop(context);
      } else {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text("Failed to add event")));
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("Add Event")),
      body: Padding(
        padding: EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: SingleChildScrollView(
            child: Column(
              children: [
                TextFormField(
                  controller: _titleController,
                  decoration: InputDecoration(labelText: "Event Title"),
                  validator: (value) => value!.isEmpty ? "Title is required" : null,
                ),
                TextFormField(
                  controller: _dateController,
                  decoration: InputDecoration(labelText: "Event Date"),
                  validator: (value) => value!.isEmpty ? "Date is required" : null,
                ),
                TextFormField(
                  controller: _timeController,
                  decoration: InputDecoration(labelText: "Event Time"),
                  validator: (value) => value!.isEmpty ? "Time is required" : null,
                ),
                TextFormField(
                  controller: _venueController,
                  decoration: InputDecoration(labelText: "Event Venue"),
                  validator: (value) => value!.isEmpty ? "Venue is required" : null,
                ),
                TextFormField(
                  controller: _avenueController,
                  decoration: InputDecoration(labelText: "Avenue"),
                  validator: (value) => value!.isEmpty ? "Avenue is required" : null,
                ),
                TextFormField(
                  controller: _descriptionController,
                  decoration: InputDecoration(labelText: "Description"),
                  validator: (value) => value!.isEmpty ? "Description is required" : null,
                ),
                TextFormField(
                  controller: _contentController,
                  decoration: InputDecoration(labelText: "Content"),
                  validator: (value) => value!.isEmpty ? "Content is required" : null,
                ),
                TextFormField(
                  controller: _contactController,
                  decoration: InputDecoration(labelText: "Contact"),
                  validator: (value) => value!.isEmpty ? "Contact is required" : null,
                ),
                SizedBox(height: 10),

                // Image URL Input
                TextFormField(
                  controller: _imageUrlController,
                  decoration: InputDecoration(labelText: "Image URL"),
                ),
                ElevatedButton(
                  onPressed: _addImageUrl,
                  child: Text("Add Image"),
                ),

                // Display added image URLs
                _imageUrls.isNotEmpty
                    ? Column(
                  children: _imageUrls
                      .map((url) => ListTile(
                    title: Text(url),
                    trailing: IconButton(
                      icon: Icon(Icons.delete, color: Colors.red),
                      onPressed: () {
                        setState(() {
                          _imageUrls.remove(url);
                        });
                      },
                    ),
                  ))
                      .toList(),
                )
                    : Container(),

                SizedBox(height: 20),
                ElevatedButton(
                  onPressed: _submitEvent,
                  child: Text("Add Event"),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
